# Generated by Django 4.2.3 on 2023-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Техника', 'Техника'), ('Бытовое', 'Бытовое'), ('Питание.', 'Питание')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('purchase_status', models.CharField(choices=[('В наличии', 'В наличии'), ('Нет наличии', 'Нет наличии')], max_length=20)),
                ('purchase_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
